### ISSUE TITLE
mac电脑，运行报错。

### ISSUE THREAD

**Issue by xfmax** [oxoooo/mr-mantou-android#9]
12-22 14:13:59.740 19738-19738/ooo.oxo.mr.debug E/MainActivity: An error occurred while fetching images
                                                                java.lang.IllegalArgumentException: value == null
                                                                    at com.avos.avoscloud.okhttp.Headers$Builder.checkNameAndValue(Headers.java:292)
                                                                    at com.avos.avoscloud.okhttp.Headers$Builder.set(Headers.java:276)
                                                                    at com.avos.avoscloud.okhttp.Request$Builder.header(Request.java:186)
                                                                    at com.avos.avoscloud.PaasClient.updateHeaders(PaasClient.java:171)
                                                                    at com.avos.avoscloud.PaasClient.getObject(PaasClient.java:404)
                                                                    at com.avos.avoscloud.PaasClient.getObject(PaasClient.java:379)
                                                                    at com.avos.avoscloud.PaasClient.getObject(PaasClient.java:311)
                                                                    at com.avos.avoscloud.AVQuery.find(AVQuery.java:1566)
                                                                    at ooo.oxo.mr.rx.RxAVQuery.lambda$find$0(RxAVQuery.java:35)
                                                                    at ooo.oxo.mr.rx.RxAVQuery.access$lambda$0(RxAVQuery.java)
                                                                    at ooo.oxo.mr.rx.RxAVQuery$$Lambda$1.call(Unknown Source)
                                                                    at rx.Observable.unsafeSubscribe(Observable.java:8098)
                                                                    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:232)
                                                                    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:142)
                                                                    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                                                                    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:202)
                                                                    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
                                                                    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                    at java.lang.Thread.run(Thread.java:856)

**Comment by xingrz** [comment]
这个项目不更新了。
